name: Subindo ao Docker Hub

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PWD}}
        run: docker login registry-1-stage.docker.io -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build && tagging
        run: docker build . --tag joaoanelli/dockerintro:0.0.${{github.run_number }}
      - name: Upload no Docker Hub
        run: docker push joaoanelli/dockerintro:0.0.${{github.run_number}}
